package by.bntu.fitr.povt.gapeenko.vlad.web.onlinelibrary.entity;
// Generated Dec 14, 2015 12:12:28 AM by Hibernate Tools 4.3.1



/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private String groupid;

    public Groups() {
    }

    public Groups(String groupid) {
       this.groupid = groupid;
    }
   
    public String getGroupid() {
        return this.groupid;
    }
    
    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }




}


